org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
pack_format_number=15

enabled_platforms=fabric,forge
fabric_loader_version=0.16.10
fabric_api_version=0.92.7+1.20.1
forge_version=1.20.1-47.4.18
forge_loader_version_range=[47,)
forge_version_range=[47,)

mod_id=raidon
mod_name=RaidON
mod_license=All Rights Reserved
mod_version=0.1.1-beta-1.20.1
mod_group_id=ru.xaoser
mod_authors=Xaoser
mod_description=This library is designed to create raids or invasions for modpacks, with convenient configuration and documentation inside.
