org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=raidon
mod_name=RaidON
mod_license=All Rights Reserved
mod_version=0.0.2-alpha
mod_group_id=ru.xaoser
mod_authors= Xaoser
mod_description= This library is designed to create raids or invasions for modpacks, with convenient configuration and documentation inside.
